### ISSUE TITLE
Internal Server Error: /api/profiles/login/ (Padding is incorrect.)

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend-service#76]
Traceback (most recent call last):
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/law-orga-backend/apps/api/views/rlc_user.py", line 116, in login
    serializer.is_valid(raise_exception=True)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/home/law-orga-backend/apps/api/serializers/rlc_user.py", line 117, in validate
    refresh = self.get_token(self.user)
  File "/home/law-orga-backend/apps/api/serializers/rlc_user.py", line 109, in get_token
    return self.token_class.for_user(user, password_user=self.initial_data['password'])
  File "/home/law-orga-backend/config/authentication.py", line 38, in for_user
    private_key = user.get_private_key(password_user=password_user)
  File "/home/law-orga-backend/apps/api/models/user.py", line 257, in get_private_key
    self.encryption_keys.decrypt(password_user)
  File "/home/law-orga-backend/apps/api/models/user_encryption_keys.py", line 45, in decrypt
    super().decrypt(key)
  File "/home/law-orga-backend/apps/static/encryption.py", line 226, in decrypt
    decrypted_field = self.encryption_class.decrypt(getattr(self, field), key)
  File "/home/law-orga-backend/apps/static/encryption.py", line 87, in decrypt
    plain = AESEncryption.decrypt_with_iv(real_encrypted, key, iv, output_type)
  File "/home/law-orga-backend/apps/static/encryption.py", line 64, in decrypt_with_iv
    plaintext_bytes = unpad(cipher.decrypt(encrypted), AES.block_size)
  File "/home/law-orga-backend/tmp/venv/lib/python3.8/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")

Request Method: POST
Exception Type: ValueError at /api/profiles/login/
Exception Value: Padding is incorrect.
Request information:
USER: AnonymousUser

**Comment by danielmoessner** [comment]
Happened with the dummy user according to logged path.
